# Part of Odoo. See LICENSE file for full copyright and licensing details.

API_VERSION = '2025-01-01'  # The API version of CashFree implemented in this module

SUPPORTED_CURRENCIES = [
    'INR',
    'USD',
    'AED',
    'AFN',
    'ALL',
    'AMD',
    'AOA',
    'ARS',
    'AUD',
    'AWG',
    'AZN',
    'BAM',
    'BBD',
    'BDT',
    'BGN',
    'BHD',
    'BIF',
    'BMD',
    'BND',
    'BRL',
    'BSD',
    'BTN',
    'BWP',
    'BYN',
    'BYR',
    'BZD',
    'CAD',
    'CDF',
    'CHF',
    'CLF',
    'CLP',
    'CNH',
    'CNY',
    'COP',
    'COU',
    'CRC',
    'CUC',
    'CUP',
    'CVE',
    'CZK',
    'DJF',
    'DKK',
    'DOP',
    'DZD',
    'EGP',
    'ERN',
    'ETB',
    'EUR',
    'FJD',
    'FKP',
    'GBP',
    'GEL',
    'GHS',
    'GIP',
    'GMD',
    'GNF',
    'GTQ',
    'GYD',
    'HKD',
    'HNL',
    'HRK',
    'HTG',
    'HUF',
    'IDR',
    'ILS',
    'IQD',
    'IRR',
    'ISK',
    'JMD',
    'JOD',
    'JPY',
    'KES',
    'KGS',
    'KHR',
    'KMF',
    'KPW',
    'KRW',
    'KWD',
    'KYD',
    'KZT',
    'LAK',
    'LBP',
    'LKR',
    'LRD',
    'LSL',
    'LTL',
    'LVL',
    'LYD',
    'MAD',
    'MDL',
    'MGA',
    'MKD',
    'MMK',
    'MNT',
    'MOP',
    'MRO',
    'MRU',
    'MUR',
    'MVR',
    'MWK',
    'MXN',
    'MYR',
    'MZN',
    'NAD',
    'NGN',
    'NIO',
    'NOK',
    'NPR',
    'NZD',
    'OMR',
    'PAB',
    'PEN',
    'PGK',
    'PHP',
    'PKR',
    'PLN',
    'PYG',
    'QAR',
    'RON',
    'RSD',
    'RUB',
    'RWF',
    'SAR',
    'SBD',
    'SCR',
    'SDG',
    'SEK',
    'SGD',
    'SHP',
    'SLE',
    'SLL',
    'SOS',
    'SRD',
    'SSP',
    'STD',
    'STN',
    'SVC',
    'SYP',
    'SZL',
    'THB',
    'TJS',
    'TMT',
    'TND',
    'TOP',
    'TRY',
    'TTD',
    'TWD',
    'TZS',
    'UAH',
    'UGX',
    'UYI',
    'UYU',
    'UYW',
    'UZS',
    'VEF',
    'VES',
    'VND',
    'VUV',
    'WST',
    'XAF',
    'XCD',
    'XOF',
    'XPF',
    'YER',
    'ZAR',
    'ZMW',
]

DEFAULT_PAYMENT_METHOD_CODES = {
    'upi',
    'netbanking',
    'card',
}

PAYMENT_METHOD_CODES_MAPPING = {
    'upi': 'upi',
    'card': 'cc, dc, ccc, ppc',
    'netbanking': 'nb',
    'paylater_india': 'paylater',
    'paypal': 'paypal',
    'emi_india': 'cardlessemi, dcemi, ccemi',
    'bank_transfer': 'banktransfer'
}

PAYMENT_METHODS_MAPPING = {
    'upi': 'upi',
    'credit_card': 'card',
    'debit_card': 'card',
    'net_banking': 'netbanking',
    'credit_card_emi': 'emi_india',
    'debit_card_emi': 'emi_india',
    'cardless_emi': 'emi_india',
    'pay_later': 'paylater_india',
    'bank_transfer': 'bank_transfer',
}

PAYMENT_STATUS_MAPPING = {
    'done': ('SUCCESS'),
    'error': ('FAILED', 'USER_DROPPED'),
    'pending': ('PENDING'),
    'cancel': ('CANCELLED'),
}

WEBHOOK_TYPE_MAPPING = {
    'payment': ("PAYMENT_SUCCESS_WEBHOOK", "PAYMENT_FAILED_WEBHOOK", "PAYMENT_USER_DROPPED_WEBHOOK"),
    'refund': ('REFUND_STATUS_WEBHOOK'),
}

# Events that are handled by the webhook.
HANDLED_WEBHOOK_EVENTS = [
    'PAYMENT_SUCCESS_WEBHOOK',
    'PAYMENT_FAILED_WEBHOOK',
    'PAYMENT_USER_DROPPED_WEBHOOK',
    'REFUND_STATUS_WEBHOOK',
]
