# Part of Odoo. See LICENSE file for full copyright and licensing details.

PROD_BASE_URL = 'info.payu.in'
TEST_BASE_URL = 'test.payu.in'

# The currencies supported by PayU, in ISO 4217 format.

SUPPORTED_CURRENCIES = [
    'INR',
    'AED',
    'AFN',
    'ALL',
    'AMD',
    'ANG',
    'AOA',
    'ARS',
    'AUD',
    'AWG',
    'AZN',
    'BAM',
    'BBD',
    'BGN',
    'BHD',
    'BIF',
    'BMD',
    'BND',
    'BOB',
    'BRL',
    'BSD',
    'BWP',
    'BYN',
    'BZD',
    'CAD',
    'CDF',
    'CHF',
    'CLP',
    'CNY',
    'COP',
    'CRC',
    'CVE',
    'CZK',
    'DJF',
    'DKK',
    'DOP',
    'DZD',
    'EGP',
    'ETB',
    'EUR',
    'FJD',
    'FKP',
    'GBP',
    'GEL',
    'GHS',
    'GIP',
    'GMD',
    'GNF',
    'GTQ',
    'GYD',
    'HKD',
    'HNL',
    'HRK',
    'HTG',
    'HUF',
    'IDR',
    'ILS',
    'IQD',
    'ISK',
    'JMD',
    'JOD',
    'JPY',
    'KGS',
    'KHR',
    'KMF',
    'KRW',
    'KWD',
    'KYD',
    'KZT',
    'LAK',
    'LBP',
    'LRD',
    'LSL',
    'MAD',
    'MDL',
    'MGA',
    'MKD',
    'MNT',
    'MOP',
    'MRU',
    'MVR',
    'MWK',
    'MXN',
    'MYR',
    'MZN',
    'NAD',
    'NGN',
    'NIO',
    'NOK',
    'NZD',
    'OMR',
    'PAB',
    'PEN',
    'PGK',
    'PLN',
    'PYG',
    'QAR',
    'RON',
    'RSD',
    'RWF',
    'SAR',
    'SBD',
    'SCR',
    'SEK',
    'SGD',
    'SHP',
    'SOS',
    'SRD',
    'SVC',
    'SZL',
    'THB',
    'TJS',
    'TMT',
    'TND',
    'TOP',
    'TRY',
    'TTD',
    'TWD',
    'TZS',
    'UGX',
    'USD',
    'UYU',
    'UZS',
    'VES',
    'VND',
    'VUV',
    'WST',
    'XAF',
    'XCD',
    'XOF',
    'XPF',
    'YER',
    'ZAR',
    'ZMW',
    'ZWL'
]

# Mapping of transaction states to Flutterwave payment statuses.
PAYMENT_STATUS_MAPPING = {
    'pending': ['pending', 'pending auth'],
    'done': ['success'],
    'cancel': ['cancel'],
    'error': ['failure'],
}

# The codes of the payment methods to activate when PayU is activated.
DEFAULT_PAYMENT_METHOD_CODES = {
    # Primary payment methods.
    'netbanking',
    'card',
    'upi',
    'wallets_india',
    'emi_india',
    'paylater_india',
    # Brand payment methods.
    'visa',
    'mastercard',
    'maestro',
    'rupay',
    'amex',
    'diners',

}

PAYU_HASH_SEQUENCE = {
    'PAYMENT': 'key|txnid|amount|productinfo|firstname|email|udf1|udf2|udf3|udf4|udf5|udf6|udf7|udf8|udf9|udf10|salt',
    "PAYMENT_WEBHOOK": "salt|status|udf10|udf9|udf8|udf7|udf6|udf5|udf4|udf3|udf2|udf1|email|firstname|productinfo|amount|txnid|key",
    'REFUND': 'key|command|var1|salt',
}

PAYMENT_METHODS_MAPPING = {
    'netbanking': ['netbanking'],
    'card': ['creditcard', 'debitcard'],
    'upi': ['upi'],
    'wallets_india': ['cashcard'],
    'emi_india': ['emi'],
    'paylater_india': ['bnpl'],
}
